import {chromium,expect} from '@playwright/test';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
await page.goto('http://localhost:5173/');
await expect(page.locator('.pending')).toHaveCount(0);
await expect(page.locator('.demo-card')).toHaveCount(9);
await page.screenshot({path:'artifacts/desktop.png'});
// Verify the retained-state contract via the actual stepper controls.
const lab=page.locator('#demo-lookahead');await lab.getByRole('button',{name:'07 Discard copy'}).click();await expect(lab.locator('.real-time')).toHaveText('0.0 s');await lab.getByRole('button',{name:'Step →'}).click();await expect(lab.locator('.real-time')).toHaveText('0.1 s');await lab.getByRole('button',{name:'Step →'}).click();await expect(lab.locator('.total')).not.toHaveText('—');
await lab.getByLabel('Mode',{exact:true}).selectOption('direct');await lab.getByRole('button',{name:'08 Advance real state'}).click();await expect(lab.locator('.real-time')).toHaveText('2.0 s');await lab.getByLabel('Mode',{exact:true}).selectOption('revamp');await lab.getByRole('button',{name:'05 Joint lookahead'}).click();await lab.screenshot({path:'artifacts/stage-2-lookahead.png'});
const bezier=page.locator('#demo-bezier');await bezier.getByRole('button',{name:'Gentle left',exact:true}).click();await expect(bezier.getByLabel('a₁ endpoint y',{exact:true})).toHaveValue('0.45');const range=bezier.getByLabel('a₁ endpoint y',{exact:true});await range.focus();await page.keyboard.press('ArrowRight');await expect(range).toHaveValue('0.46');const canvas=bezier.locator('canvas');await canvas.scrollIntoViewIfNeeded();const box=await canvas.boundingBox();const oldEndpoint=await bezier.getByLabel('a₁ endpoint x',{exact:true}).inputValue();const point=await page.evaluate(()=>({x:7.6,y:1.84}));const scale=340/20;const px=box.x+(400+(point.x-10.5)*scale)/800*box.width;const py=box.y+(170-point.y*scale)/340*box.height;await page.mouse.move(px,py);await page.mouse.down();await page.mouse.move(px+10,py-4,{steps:4});await page.mouse.up();expect(await bezier.getByLabel('a₁ endpoint x',{exact:true}).inputValue()).not.toBe(oldEndpoint);await bezier.screenshot({path:'artifacts/stage-2-bezier.png'});
const results=page.locator('#demo-results');await results.getByRole('button',{name:'WOSAC',exact:true}).click();await expect(results.locator('.notice')).toContainText('not a controlled baseline');await expect(results.locator('table')).toContainText('0.702');await results.screenshot({path:'artifacts/stage-3-results.png'});
await results.getByRole('button',{name:'Robustness',exact:true}).click();await expect(results.locator('tbody tr')).toHaveCount(9);
const corruption=page.locator('#demo-corruption');await corruption.getByLabel('Table V metric',{exact:true}).selectOption('alignment');await expect(corruption.locator('.heatmap')).toContainText('-0.231');await corruption.getByRole('button',{name:'Resample',exact:true}).click();await corruption.screenshot({path:'artifacts/stage-4-corruption.png'});
const reward=page.locator('#demo-reward');await reward.getByLabel('Scenario',{exact:true}).selectOption('collision');await reward.screenshot({path:'artifacts/stage-4-reward.png'});
const comparison=page.locator('#demo-comparison');await comparison.getByRole('button',{name:'Intersection',exact:true}).click();await comparison.getByRole('button',{name:'Step →'}).click();await expect(comparison.locator('.frame-time')).toContainText('0.1 s');await comparison.locator('input[type=file]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});await expect(comparison.locator('.load-status')).toContainText('Could not load');await comparison.locator('input[type=file]').setInputFiles(['public/rollouts/intersection-direct1.json','public/rollouts/intersection-direct20.json','public/rollouts/intersection-revamp.json']);await expect(comparison.locator('.load-status')).toContainText('Loaded 3');await comparison.screenshot({path:'artifacts/stage-5-comparison.png'});
// Playback pauses, reset works, and offscreen simulation does not advance.
const selfplay=page.locator('#demo-selfplay');await selfplay.getByRole('button',{name:'▶ Play',exact:true}).click();await expect(selfplay.getByRole('button',{name:'Ⅱ Pause',exact:true})).toBeVisible();await selfplay.getByRole('button',{name:'Ⅱ Pause',exact:true}).click();await selfplay.getByRole('button',{name:'↺ Reset',exact:true}).click();
await lab.getByRole('button',{name:'↺ Reset',exact:true}).click();await lab.getByRole('button',{name:'▶ Play',exact:true}).click();await page.locator('#citation').scrollIntoViewIfNeeded();await page.waitForTimeout(500);const before=await lab.locator('.step-description').textContent();await page.waitForTimeout(1000);expect(await lab.locator('.step-description').textContent()).toBe(before);await lab.getByRole('button',{name:'Ⅱ Pause',exact:true}).click();
await page.locator('#theme').click();await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:'artifacts/dark.png'});await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');await page.locator('#theme').click();
const mobile=await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto('http://localhost:5173/');await expect(mobile.locator('.pending')).toHaveCount(0);await mobile.screenshot({path:'artifacts/mobile.png'});const dimensions=await mobile.evaluate(()=>({scroll:document.documentElement.scrollWidth,viewport:innerWidth}));expect(dimensions.scroll).toBeLessThanOrEqual(dimensions.viewport);await mobile.locator('#demo-lookahead').screenshot({path:'artifacts/mobile-lookahead.png',style:'.section-nav,.skip-link{visibility:hidden!important}'});await mobile.locator('#demo-results').getByRole('button',{name:'WOSAC',exact:true}).click();await expect(mobile.locator('#demo-results table')).toContainText('0.702');
expect(errors).toEqual([]);console.log('Browser checks passed: nine demos, retained time, input controls, charts, JSON validation, playback, offscreen pause, themes, and mobile overflow.');await browser.close();
