import {params} from '../data/params';
export const $=<T extends Element=HTMLElement>(root:ParentNode,selector:string)=>root.querySelector<T>(selector)!;
export function button(text:string,fn:()=>void,className=''):HTMLButtonElement {const b=document.createElement('button');b.type='button';b.textContent=text;b.className=className;b.onclick=fn;return b;}
export function range(root:HTMLElement,label:string,min:number,max:number,step:number,value:number,onchange:(v:number)=>void){const el=document.createElement('label');el.className='range-control';el.innerHTML=`<span>${label}<output>${value}</output></span><input type="range" min="${min}" max="${max}" step="${step}" value="${value}" aria-label="${label}">`;const input=$<HTMLInputElement>(el,'input'),output=$(el,'output');input.oninput=()=>{output.textContent=input.value;onchange(+input.value);};root.append(el);return input;}
export function select(root:HTMLElement,label:string,options:[string,string][],change:(v:string)=>void){const l=document.createElement('label');l.className='select-control';const text=document.createElement('span');text.textContent=label;const s=document.createElement('select');s.setAttribute('aria-label',label);options.forEach(([v,t])=>{const o=document.createElement('option');o.value=v;o.textContent=t;s.append(o);});s.onchange=()=>change(s.value);l.append(text,s);root.append(l);return s;}
export function check(root:HTMLElement,label:string,initial:boolean,change:(b:boolean)=>void){const l=document.createElement('label');l.className='check';const i=document.createElement('input');i.type='checkbox';i.checked=initial;i.onchange=()=>change(i.checked);l.append(i,document.createTextNode(label));root.append(l);return i;}
export function tabs(root:HTMLElement,items:[string,string][],initial:string,onchange:(v:string)=>void){const group=document.createElement('div');group.className='tabs';group.setAttribute('role','group');items.forEach(([key,label])=>{const b=button(label,()=>{group.querySelectorAll('button').forEach(x=>{x.setAttribute('aria-pressed',String(x===b));});onchange(key);});b.setAttribute('aria-pressed',String(key===initial));group.append(b);});root.append(group);return group;}
/** Each demo owns its own playback. Offscreen and background tabs never advance. */
export function transport(root:HTMLElement,tick:(dt:number)=>void,reset:()=>void,step?:()=>void){
 let playing=false,visible=false,last=0;const bar=document.createElement('div');bar.className='transport';const play=button('▶ Play',()=>{playing=!playing;play.textContent=playing?'Ⅱ Pause':'▶ Play';play.setAttribute('aria-pressed',String(playing));},'primary');play.setAttribute('aria-pressed','false');bar.append(play,button('↺ Reset',()=>{playing=false;play.textContent='▶ Play';play.setAttribute('aria-pressed','false');reset();}));if(step)bar.append(button('Step →',step));root.append(bar);
 const obs=new IntersectionObserver(es=>{visible=es[0].isIntersecting;},{rootMargin:'50px'});obs.observe(root);
 function frame(now:number){if(playing&&visible&&!document.hidden)tick(Math.min(params.playback.maxFrameDt,(now-last)/1000||0));last=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);
 return {bar,pause:()=>{playing=false;play.textContent='▶ Play';play.setAttribute('aria-pressed','false');},get playing(){return playing;}};
}
export function hint(root:HTMLElement,text:string){const p=document.createElement('p');p.className='hint';p.textContent='↳ '+text;root.append(p);}
