import {params,type RewardCoefficients} from '../../data/params';
import {initialWorld,plansFor,policy,advance,type Scenario} from '../../lib/simulation';
import {reward,weight,termNames,sumTerms,goalTerm,controlPointTerm,isOffroad,type Terms} from '../../lib/rewards';
import {decode} from '../../lib/bezier';
import {collides} from '../../lib/vehicle';
import {$,select,range,transport,hint,button,check} from '../../ui/controls';
export function mount(root:HTMLElement){
 root.innerHTML=`<div class="demo-header"><h3 class="demo-title">Lookahead reward explorer</h3><span class="tag">Illustrative coefficients</span></div><div class="demo-body"><div class="controls"></div><div class="formula">r<sub>look</sub> = r<sub>control</sub> + Σ cₖ qₖ + R<sub>goal</sub>(Nss − k<sub>g</sub>)</div><div class="legend"></div><div class="reward-chart"></div><div class="stats"><div class="stat"><span>Weighted rollout Σ cₖqₖ</span><strong class="weighted"></strong></div><div class="stat"><span>One-time control-point term</span><strong class="control-value"></strong></div><div class="stat"><span>Goal term</span><strong class="goal-value"></strong></div><div class="stat"><span>Total r_look</span><strong class="look-total"></strong></div></div><details><summary>Edit illustrative coefficients</summary><div class="coefficient-grid"></div><div class="coefficient-buttons transport"></div><p>Tables VI and VII were not included in the prompt. Paper reset is unavailable until those values are supplied. These coefficients and term definitions are for explanation only.</p></details><div class="playback"></div><p class="selected-step micro" aria-live="polite"></p></div><div class="demo-footer">Section IV-C · Eq. 19–20 aggregation as specified. Appendix C constants and exact term definitions await PDF verification. Goal bonus applies once, only if a goal is reached at k_g.</div>`;
 const colors=['#8fac89','#d4b976','#40866c','#b36252','#7185a0'];const tips=['Alignment with the road; illustrative lateral error penalty.','Efficiency; illustrative normalized speed.','Progress toward the goal; illustrative forward displacement.','Collision penalty for overlapping vehicle rectangles.','Off-road penalty when the vehicle exceeds road bounds.'];
 $(root,'.legend').innerHTML=termNames.map((k,i)=>`<span title="${tips[i]}" tabindex="0"><i style="background:${colors[i]}"></i>${k}</span>`).join('');let c:RewardCoefficients={...params.reward},n=20,dt=.1,scenario:Scenario='avoid',stop=true,selected=0,acc=0,control=0,terms:Terms[]=[],kg:number|undefined;
 select($(root,'.controls'),'Scenario',[['avoid','Obstacle avoidance'],['collision','Collision course'],['offroad','Road departure'],['goal','Goal approach']],v=>{scenario=v as Scenario;calculate();});range($(root,'.controls'),'Nss',1,20,1,n,v=>{n=v;calculate();});range($(root,'.controls'),"Δt′ (s)",.05,.3,.05,dt,v=>{dt=v;calculate();});check($(root,'.controls'),'Stop temporary rollout on event',true,v=>{stop=v;calculate();});
 const inputs:HTMLInputElement[]=[];Object.keys(c).forEach(key=>{const k=key as keyof RewardCoefficients,l=document.createElement('label');l.textContent=k;const i=document.createElement('input');i.type='number';i.step='.1';i.value=String(c[k]);i.setAttribute('aria-label',`${k} coefficient`);i.onchange=()=>{if(!Number.isFinite(i.valueAsNumber)){i.value=String(c[k]);return;}c[k]=i.valueAsNumber;calculate();};inputs.push(i);l.append(i);$(root,'.coefficient-grid').append(l);});
 $(root,'.coefficient-buttons').append(button('Reset demo defaults',()=>{c={...params.reward};inputs.forEach((v,i)=>v.value=String(Object.values(c)[i]));calculate();}));const unavailable=button('Reset to paper values · PDF needed',()=>{});unavailable.disabled=true;unavailable.title='Appendix C Tables VI and VII have not been supplied';$(root,'.coefficient-buttons').append(unavailable);
 function calculate(){const world=initialWorld();if(scenario==='goal'){world.agents[0].x=30;world.agents[0].y=-3;}const paths=plansFor(world,scenario);control=controlPointTerm(decode(policy(world.agents[0],scenario),world.agents[0].speed).ends,c.control);terms=[];kg=undefined;
 for(let k=1;k<=n;k++){const prev=structuredClone(world.agents[0]);advance(world,paths,dt);const ego=world.agents[0];terms.push(reward(ego,prev,world.agents,c));if(kg===undefined&&ego.x>=params.scene.goalX)kg=k;if(stop&&(collides(ego,params.scene.obstacle)||world.agents.slice(1).some(v=>collides(ego,v))||isOffroad(ego)))break;}
 selected=Math.min(selected,terms.length-1);draw();}
 function draw(){const rows=terms.map((t,i)=>termNames.map(k=>t[k]*weight(i+1,n)));const max=Math.max(.01,...rows.map(v=>v.filter(x=>x>0).reduce((a,b)=>a+b,0))),min=Math.min(-.01,...rows.map(v=>v.filter(x=>x<0).reduce((a,b)=>a+b,0)));const h=190,scale=h/(max-min),zero=30+max*scale,bw=700/n;
 $(root,'.reward-chart').innerHTML=`<svg class="chart" viewBox="0 0 800 270" role="img" aria-label="Stacked positive and negative weighted reward contributions by lookahead step"><line class="grid" x1="48" x2="770" y1="${zero}" y2="${zero}"/><text x="6" y="${zero+4}" class="muted">0</text><text x="0" y="30" class="muted">${max.toFixed(2)}</text><text x="0" y="220" class="muted">${min.toFixed(2)}</text>${rows.map((r,i)=>{let pos=zero,neg=zero;return `<g tabindex="0" role="button" aria-label="Inspect reward step ${i+1}" data-k="${i}" style="cursor:pointer">${r.map((v,j)=>{const height=Math.abs(v)*scale;let y;if(v>=0){pos-=height;y=pos;}else{y=neg;neg+=height;}return `<rect x="${50+i*bw}" y="${y}" width="${bw-5}" height="${Math.max(.5,height)}" fill="${colors[j]}" opacity="${i===selected?1:.65}"><title>${termNames[j]}: ${v.toFixed(4)}</title></rect>`;}).join('')}<rect x="${49+i*bw}" y="22" width="${bw-3}" height="205" fill="transparent" stroke="${i===selected?'#176754':'transparent'}"/><text x="${50+i*bw+(bw-5)/2}" y="244" text-anchor="middle" class="muted">${i+1}</text></g>`;}).join('')}<text x="640" y="266" class="muted">Lookahead substep k →</text></svg>`;
 root.querySelectorAll<SVGGElement>('[data-k]').forEach(g=>{const pick=()=>{selected=Number(g.dataset.k);describe();};g.onclick=()=>{pick();draw();};g.onfocus=pick;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick();draw();}};});
 const weighted=terms.reduce((s,t,i)=>s+sumTerms(t)*weight(i+1,n),0),goal=goalTerm(n,kg,c.goal);$(root,'.weighted').textContent=weighted.toFixed(3);$(root,'.control-value').textContent=control.toFixed(3);$(root,'.goal-value').textContent=goal.toFixed(3);$(root,'.look-total').textContent=(weighted+control+goal).toFixed(3);describe();}
 function describe(){const t=terms[selected];$(root,'.selected-step').textContent=`k = ${selected+1} · cₖ = ${weight(selected+1,n).toFixed(4)} · qₖ = ${sumTerms(t).toFixed(3)} · ${termNames.map(k=>`${k}: ${t[k].toFixed(3)}`).join(' / ')}${kg===undefined?' · goal not reached':` · goal at k=${kg}`}`;}
 transport($(root,'.playback'),delta=>{acc+=delta;if(acc>.5){acc=0;selected=(selected+1)%terms.length;draw();}},()=>{selected=0;calculate();},()=>{selected=(selected+1)%terms.length;draw();});hint($(root,'.demo-body'),'Choose a collision course to see how a future safety penalty changes the reward before the real car reaches the obstacle.');calculate();
}
