import {resolutionResults,metricInfo,type Metric} from '../../data/results';
import {$,transport,hint} from '../../ui/controls';
export function mount(root:HTMLElement){
 root.innerHTML=`<div class="demo-header"><h3 class="demo-title">Resolution trade-off</h3><span class="tag">Table IV</span></div><div class="demo-body"><div class="split split-wide"><div class="scatter"></div><aside class="aside point-details" aria-live="polite"></aside></div><div class="playback"></div><p class="notice">(10, 0.2) is the favorable compromise. (7, 0.3) degrades badly: ${resolutionResults[0].metrics.success!.mean.toFixed(2)}% success and ${resolutionResults[0].metrics.dnf!.mean.toFixed(2)}% DNF, with high variance. Marker area encodes DNF; bars show success ± SD.</p></div><div class="demo-footer">Table IV · Throughput (thousands of simulator steps / second) versus success. Hover, focus, or click a point for every reported metric.</div>`;
 let selected=1,acc=0;const x=(v:number)=>75+(v-100)/35*450,y=(v:number)=>260-(v-45)/55*215;
 function draw(){const lines=resolutionResults.map(r=>`${x(r.metrics.sps!.mean)},${y(r.metrics.success!.mean)}`).join(' ');$(root,'.scatter').innerHTML=`<svg class="chart" viewBox="0 0 620 320" role="img" aria-label="Success versus throughput: 10 steps at 0.2 seconds balances speed and success.">${[50,60,70,80,90,100].map(v=>`<line class="grid" x1="75" x2="550" y1="${y(v)}" y2="${y(v)}"/><text class="muted" x="35" y="${y(v)+4}">${v}%</text>`).join('')}<polyline points="${lines}" fill="none" stroke="#a4b99d" stroke-width="2" stroke-dasharray="5 5"/>${[105,115,125,135].map(v=>`<text class="muted" x="${x(v)}" y="287" text-anchor="middle">${v}k</text>`).join('')}${resolutionResults.map((r,i)=>{const m=r.metrics,px=x(m.sps!.mean),py=y(m.success!.mean);return `<g tabindex="0" role="button" aria-label="${r.label}, success ${m.success!.mean} percent" data-point="${i}" style="cursor:pointer"><line x1="${px}" x2="${px}" y1="${y(m.success!.mean-m.success!.sd!)}" y2="${y(m.success!.mean+m.success!.sd!)}" stroke="#72967c"/><circle cx="${px}" cy="${py}" r="${7+Math.sqrt(m.dnf!.mean)*3}" fill="${i===selected?'#176754':'#9db99e'}" fill-opacity=".8" stroke="${i===selected?'#176754':'#edf2e9'}" stroke-width="3"/><text x="${px+16}" y="${py-14}" style="font-size:10px">${r.label}</text></g>`;}).join('')}<text x="75" y="18">Success ↑</text><text x="270" y="314" class="muted">Throughput · SPS →</text></svg>`;
 root.querySelectorAll<SVGGElement>('[data-point]').forEach(g=>{const pick=()=>{selected=Number(g.dataset.point);detail();};g.onmouseenter=pick;g.onfocus=pick;g.onclick=()=>{pick();draw();};g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();pick();draw();}};});detail();}
 function detail(){const r=resolutionResults[selected];$(root,'.point-details').innerHTML=`<h4>${r.label}${selected===1?' · favorable compromise':''}</h4>${Object.entries(r.metrics).map(([key,m])=>`<div class="reward-line"><span>${metricInfo[key as Metric].label}</span><strong>${m.mean}${m.sd!==undefined?` ± ${m.sd}`:''}</strong></div>`).join('')}`;}
 transport($(root,'.playback'),dt=>{acc+=dt;if(acc>2){acc=0;selected=(selected+1)%3;draw();}},()=>{selected=1;draw();},()=>{selected=(selected+1)%3;draw();});hint($(root,'.demo-body'),'Compare the middle setting to the fastest one: a modest throughput gain can carry a large failure cost.');draw();
}
