import {params} from '../../data/params';
import {syntheticRollout,validateRollout,methodNames,type Rollout} from '../../lib/rollout';
import {Scene} from '../../ui/canvas';
import {$,tabs,transport,check,hint} from '../../ui/controls';
import {drawAttention} from '../attention';
export function mount(root:HTMLElement){
 root.innerHTML=`<div class="demo-header"><h3 class="demo-title">Synchronized qualitative comparison</h3><span class="tag">Synthetic placeholders</span></div><div class="demo-body"><div class="scenario-tabs"></div><div class="controls"></div><div class="comparison-grid"></div><label class="range-control"><span>Shared timeline<output class="frame-time">0.0 s</output></span><input type="range" class="scrubber" aria-label="Comparison time" min="0" max="99" step="1" value="0"></label><div class="playback"></div><p class="interpretation notice"></p><details><summary>Load real rollout JSON files</summary><label class="upload-label">Choose up to three method files for the current scenario.<input type="file" accept="application/json,.json" multiple></label><p class="load-status" role="status">Each file is validated before display. Uploaded scene labels are shown as text.</p></details></div><div class="demo-footer">Qualitative comparison · Interpretations below paraphrase the supplied specification. These synthetic scenes illustrate the viewing interface; they are not evidence of policy performance.</div>`;
 const methods:Rollout['method'][]=['direct1','direct20','revamp'];const scenes=methods.map(m=>{const panel=document.createElement('div');panel.className='comparison-panel';panel.innerHTML=`<h4>${methodNames[m]}</h4>`;$(root,'.comparison-grid').append(panel);return new Scene(panel,{xmin:-5,xmax:55,ymin:-12,ymax:18},`${methodNames[m]} replay`);});
 let scenario='curved',rollouts=methods.map(m=>syntheticRollout(scenario,m)),frame=0,showPlan=true,attention=false,acc=0,request=0;
 const scrub=$<HTMLInputElement>(root,'.scrubber');scrub.oninput=()=>{frame=+scrub.value;draw();};
 const descriptions:Record<string,string>={curved:'On a curved road, the supplied interpretation highlights Direct Nss = 1’s unexecuted path crossing the obstacle, Direct Nss = 20 leaving excessive clearance, and REVAMP producing a decisive path with adequate clearance. The traces above are synthetic illustrations, not the paper’s rollouts.',intersection:'At an intersection, compare the predicted paths of interacting agents and the frequency with which each plan changes. REVAMP’s temporary joint rollout is intended to evaluate interactions while preserving frequent replanning. These synthetic traces do not establish comparative safety.',overtaking:'During overtaking, compare the future path with the small portion currently being executed. The supplied interpretation describes REVAMP as decisive with adequate clearance, while Direct Nss = 20 may be overcautious. Real recorded rollouts are needed to verify that behavior.'};
 function limit(){return Math.min(...rollouts.map(r=>r.frames.length))-1;}
 async function load(){const version=++request;const loaded=await Promise.all(methods.map(async m=>{try{const r=await fetch(`${import.meta.env.BASE_URL}rollouts/${scenario}-${m}.json`);if(!r.ok)throw new Error('No asset');const parsed=validateRollout(await r.json());if(parsed.method!==m||parsed.scenario!==scenario)throw new Error('Asset scenario/method mismatch');return parsed;}catch{return syntheticRollout(scenario,m);}}));if(version===request){const valid=loaded.every(r=>r.frames.length===loaded[0].frames.length&&r.frames.every((f,i)=>Math.abs(f.t-loaded[0].frames[i].t)<1e-6));rollouts=valid?loaded:methods.map(m=>syntheticRollout(scenario,m));if(!valid)$(root,'.load-status').textContent='Packaged recordings have different frame times; showing synthetic placeholders.';frame=0;draw();}}
 function draw(){frame=Math.min(frame,limit());rollouts.forEach((r,i)=>{const s=scenes[i],f=r.frames[frame];const points=r.map.roads.flat();if(points.length){const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]);s.view={xmin:Math.min(...xs)-5,xmax:Math.max(...xs)+5,ymin:Math.min(...ys)-10,ymax:Math.max(...ys)+10};}s.clear();r.map.roads.forEach(line=>s.path(line.map(([x,y])=>({x,y})),'#dfe3dc',14*s.scale));r.map.edges.forEach(line=>s.path(line.map(([x,y])=>({x,y})),'#9cab98',1));r.map.roads.forEach(line=>s.path(line.map(([x,y])=>({x,y})),'#f8faf5',1.5,true));r.obstacles.forEach(v=>s.vehicle(v,'obstacle'));s.dot({x:r.map.goal[0],y:r.map.goal[1]},'GOAL','#839e72',3);if(showPlan)f.agents.forEach(a=>{if(a.plan)s.path(a.plan.map(([x,y])=>({x,y})),a.id===0?'#176754':'#849987',2,true);});f.agents.forEach(a=>s.vehicle(a,a.id===0?'ego':'other'));if(attention)drawAttention(s,r,f.agents);s.label(r.synthetic?'SYNTHETIC PLACEHOLDER':'LOADED ROLLOUT');});scrub.max=String(limit());scrub.value=String(frame);$(root,'.frame-time').textContent=`${rollouts[0].frames[frame].t.toFixed(1)} s · frame ${frame+1}`;$(root,'.interpretation').textContent=descriptions[scenario];$(root,'.tag').textContent=rollouts.every(r=>r.synthetic)?'Synthetic placeholders':rollouts.some(r=>r.synthetic)?'Mixed · loaded & synthetic':'Loaded rollouts';}
 tabs($(root,'.scenario-tabs'),[['curved','Curved road'],['intersection','Intersection'],['overtaking','Overtaking']],'curved',v=>{scenario=v;rollouts=methods.map(m=>syntheticRollout(v,m));frame=0;draw();void load();});check($(root,'.controls'),'Show predicted 2 s paths',true,v=>{showPlan=v;draw();});if(params.featureFlags.attention)check($(root,'.controls'),'Encoder attention · additional analysis, not in the paper',false,v=>{attention=v;draw();});
 const player=transport($(root,'.playback'),dt=>{acc+=dt;if(acc>=params.dt){acc-=params.dt;frame=(frame+1)%(limit()+1);draw();}},()=>{frame=0;acc=0;draw();},()=>{frame=(frame+1)%(limit()+1);draw();});
 $<HTMLInputElement>(root,'input[type=file]').onchange=async e=>{player.pause();++request;const files=[...(e.target as HTMLInputElement).files??[]];try{if(files.length>3)throw new Error('Choose at most three files.');const parsed=await Promise.all(files.map(async f=>validateRollout(JSON.parse(await f.text()))));if(new Set(parsed.map(r=>r.method)).size!==parsed.length)throw new Error('Choose one file per method.');if(parsed.some(r=>r.scenario!==scenario))throw new Error(`Files must use scenario "${scenario}" for this tab.`);const candidate=methods.map((m,i)=>parsed.find(r=>r.method===m)??rollouts[i]);if(candidate.some(r=>r.frames.length!==candidate[0].frames.length||r.frames.some((f,i)=>Math.abs(f.t-candidate[0].frames[i].t)>1e-6)))throw new Error('Synchronized rollouts need identical frame times. Load all three together to replace the timeline.');rollouts=candidate;frame=0;draw();$(root,'.load-status').textContent=`Loaded ${parsed.length} validated rollout(s).`;}catch(err){$(root,'.load-status').textContent=`Could not load: ${(err as Error).message}`;}};
 hint($(root,'.demo-body'),'Scrub all three methods together, then toggle the predicted paths to separate a plan from its execution.');draw();void load();
}
